config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path: 'admin', controllers: { sessions: 'users/sessions' }, skip: 'registration'

  resource :admin, controller: 'admin', only: [:show]

  namespace 'admin' do
		resources :news
  end

  resource :static, only: [:show, :create]

  root 'statics#show'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :email, :name, :message

  validates_presence_of :email
  validates_presence_of :name
  validates_presence_of :message
end

app/models/new.rb
class New < ActiveRecord::Base
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < AdminController
  def new
    @new = New.new
  end

  def create
    @new = New.new(new_params)

    respond_to do |format|
      if @new.save
        format.html { redirect_to admin_path }
        flash[:notice] = 'News créée avec succèes'
      else
        flash.now[:error] = @new.errors.full_messages.join("<br />")
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @new = New.find(params[:id])
  end

  def update
    @new = New.find(params[:id])
    @new.update!(new_params)

    redirect_to admin_path, notice: 'News mise à jour avec succèes'
  end

  def destroy
    @new = New.find(params[:id])
    @new.destroy!

    redirect_to admin_path, alert: 'News supprimée avec succèes'
  end

  private

  def new_params
    params.require(:new).permit(:news)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'

	before_action :authenticate_admin!

	def show
		@new = New.first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def show
    @contact = Contact.new()
    @new = New.first

    render 'statics/show'
  end

  def create
    @contact = Contact.new()

    @contact = params[:contact]

    flash[:notice] = "Message envoyé"
    Mailer.contact(@contact).deliver
    redirect_to action: 'show'
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :message)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	layout 'admin'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/news/_form.html.erb
<%= form_for(["admin", @new]) do |f| %>
	<%= f.label "news" %><br />
	<%= f.text_area "news", class: "news-area" %><br /><br />
	<%= f.submit 'Mettre à jour à la news', class: 'btn btn-success' %>
<% end %>

app/views/admin/news/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/news/new.html.erb
<%= form_for(["admin", @new], url: { action: :create }) do |f| %>
	<%= f.label "news" %><br />
	<%= f.text_area "news", class: "news-area" %><br /><br />
	<%= f.submit 'Créer la news', class: 'btn btn-success' %>
<% end %>

app/views/admin/show.html.erb
<%= link_to "Déconnexion", destroy_admin_session_path, method: "delete", class: "btn btn-danger logout" %>
<section>
	<article>
		<h2>Gestion de la news :</h2>
		<% if @new.present? %>
			<%= @new.news %><br /><br />
			<%= link_to 'Mettre à jour', edit_admin_news_path(@new.id), class: 'btn btn-success' %>
			<%= link_to 'Delete', admin_news_path(@new.id), method: :delete, class: 'btn btn-danger' %>
		<% else %>
			<%= link_to 'Céer une news', new_admin_news_path, class: 'btn btn-success' %>
		<% end %>
	</article>
</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Infinity Institut</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="content">
    <h1>Admin Infinity Institut</h1>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="keywords" content="institut, infinity institut, institut beauté, cheseaux, cheseaux-sur-lausanne" />
  <meta name="description" content="Infinity Institut - Institut de Beauté - Rue de la Mèbre 15, 1033 Cheseaux-sur-Lausanne" />
  <meta name="author" content="Infinity Institut" />
  <title>Infinity Institut - Rue de la Mèbre 15, 1033 Cheseaux-sur-Lausanne - Institut de Beauté</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1 id="logo">Infinity Institut - Rue de la Mèbre 15, 1033 Cheseaux-sur-Lausanne - Institut de Beauté</h1>
    <nav id="sticky-nav">
      <ul>
        <li><a href="infinity" class="active">Infinity Institut</a></li>
        <li><a href="prestations">Prestations</a></li>
        <li><a href="contact">Contact</a></li>
        <a class="fb-link" href="https://www.facebook.com/infinityinstitut" target="_blank"><i class="fb-icon"></i></a>
      </ul>
    </nav>
    <div class="gradient"></div>
  </header>
  <div class="content">
		<%= yield %>
	</div>
  <script>
      function initialize() {
        var mapCanvas = document.getElementById('map');
        var mapOptions = {
          center: new google.maps.LatLng(46.582107, 6.607316),
          zoom: 17,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</body>
</html>